### ISSUE TITLE
关于屏蔽多个IP的问题

### ISSUE THREAD

**Issue by 738NGX** [galtjay/warpforvps#1]
我现在一开始的IP是104.28.211.105，用这个脚本屏蔽之后切换到了104.28.243.105用了一上午又不行了，但是我新开一个docker屏蔽这个IP之后似乎并没有同时起效，所以应该怎么解决？
![image](https://github.com/galtjay/warpforvps/assets/79038651/2e53675d-68da-4c0d-80f8-642d72295601)

**Comment by galtjay** [comment]
需要我改脚本。有空处理。

**Comment by galtjay** [comment]
兄弟，我把屏蔽多个IP的功能加上去了，测试了一下没问题，希望能帮到你。
