### ISSUE TITLE
[Resolved] not work in OpenWRT docker

### ISSUE THREAD

**Issue by Arthur2012** [galtjay/warpforvps#2]
It's not working in OpenWRT based docker, see port 40000 is not running.
But it's working in RouterOS based docker, port 40000 is ok.

in OpenWRT based docker:
root@cloudflare_warp:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4244  3120 ?        Ss   11:33   0:00 /bin/bash /init.sh
root         9  0.2  0.2  33904 21224 ?        Ss   11:33   0:00 /usr/bin/python3 /usr/bin/supervisord
root        11  3.2  0.5 1543736 46580 ?       Dl   11:33   0:02 /usr/bin/warp-svc
root        28  0.1  0.0   4508  3684 pts/0    Ss   11:33   0:00 /bin/bash
root        46  0.0  0.0   2668   920 ?        S    11:33   0:00 tail -f /var/log/warp.log
root        57  0.0  0.0   6864  1556 pts/0    R+   11:34   0:00 ps aux
root@cloudflare_warp:/#
root@cloudflare_warp:/# netstat -lnptu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
root@cloudflare_warp:/#

in RouterOS based docker:
0;root@warp01: /root@warp01:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4244  3284 ?        S    16:40   0:00 /bin/bash /init.sh
root         3  0.0  0.2  33904 21212 ?        Ss   16:40   0:02 /usr/bin/python3 /usr/bin/supervisord
root         5  0.1  0.5 1543416 44620 ?       Sl   16:40   0:24 /usr/bin/warp-svc
root        32  0.0  0.0   2668   912 ?        S    16:40   0:00 tail -f /var/log/warp.log
root        87  0.0  0.0   6864  1632 ?        R+   20:14   0:00 ps aux
0;root@warp01: /root@warp01:/# 
0;root@warp01: /root@warp01:/# 
0;root@warp01: /root@warp01:/# netstat -lnptu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:40000           0.0.0.0:*               LISTEN      5/warp-svc          
0;root@warp01: /root@warp01:/#

**Comment by galtjay** [comment]
use docker host mode please.

**Comment by Arthur2012** [comment]
Status update: The problem was **solved**.
The issue reason is that warp client "warp-svc" can't connect the warp server with UDP port 2408. If the connection setup successful, then warp-svc will start listening on port 40000.
The reason UDP connection failed is that the OpenWRT app **"ShadowSocksR Plus+" has a bug of proxying localhost UDP traffic**, however it works for proxying non-localhost UDP traffic.
So the solution is to use "**PassWall**" app in OpenWRT, which has no bug for proxying local UDP traffic. Then this warp docker works fine in OpenWRT.

**Comment by galtjay** [comment]
ok,thanks for the message.
