### ISSUE TITLE
能否指导怎么用吗？

### ISSUE THREAD

**Issue by tianlichunhong** [galtjay/warpforvps#3]
我使用docker-compose，脚本如下。但是发现用不了。
使用命令检测检测socks5是否正常curl -x socks5://127.0.0.1:40000 ipinfo.io，发现socks5不通。用vps的公网地址也不行。

 warp:
    container_name: warp
    image: galtjay/warp:v3
    network_mode: host
    environment:
        myip: "XXXX"      
    restart: unless-stopped

**Comment by galtjay** [comment]
不要使用-p选项，使用host模式。ss -tnlp查看一下本地端口的启动情况，最终再用本地代理进行测试。理论上肯定是可以用的。

**Comment by galtjay** [comment]
已经在github回复，使用-p选项可能会有问题，建议使用host模式。你先看看，假如有问题，截图发我。

Wilson ***@***.***> 于2023年10月14日周六 21:46写道：
