### ISSUE TITLE
Unable to connect to CloudflareWARP daemon. Maybe the daemon is not running?

### ISSUE THREAD

**Issue by eromoe** [galtjay/warpforvps#4]
```
docker run -d --name warp --network host galtjay/warp:v3

docker exec -it warp /bin/bash

warp-cli disconnect && sleep 3 &&warp-cli connect && sleep 3&& export ALL_PROXY=socks5://127.0.0.1:40000 && curl https://chat.openai.com/cdn-cgi/trace
```

然后就报这个错误

**Comment by eromoe** [comment]
supervisorctl
warp-svc                         BACKOFF   Exited too quickly (process log may have details)
supervisor> restart warp-svc
warp-svc: stopped
warp-svc: ERROR (spawn error)
supervisor> tail warp-svc
display a backtrace
thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /home/vsts_azpcontainer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /home/vsts_azpcontainer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /home/vsts_azpcontainer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /home/vsts_azpcontainer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /home/vsts_azpcontainer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by eromoe** [comment]
我的宿主机上有装supervisor ， 会不会是什么冲突了？

**Comment by galtjay** [comment]
你尝试把本机的supervisor 卸载看看？
